name: Deploy Neamsoft Website CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Environment File
        run: |
          mkdir -p src/environments
          # Creando archivo local (por requerimiento de compilador)
          cp src/environments/environment.ts.example src/environments/environment.ts
          sed -i "s|SENDMAIL_URL_PLACEHOLDER|${{ secrets.SENDMAIL_URL }}|g" src/environments/environment.ts
          
          # Creando archivo prod y activando el flag production: true
          cp src/environments/environment.ts.example src/environments/environment.prod.ts
          sed -i "s|production: false|production: true|g" src/environments/environment.prod.ts
          sed -i "s|SENDMAIL_URL_PLACEHOLDER|${{ secrets.SENDMAIL_URL }}|g" src/environments/environment.prod.ts

      - name: Build Application
        run: npx ng build --configuration production

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync dist/neamsoft/browser/ s3://${{ vars.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"
